id: P5E33E8E8
initial_creation_type: ocr
source_metadata:
  volumes:
    491762629d604a128501924935c56bf9:
      base_file: v089.txt
      image_group_id: I1PD95934
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ་མངོན་པར་བརྗོད་པ་རང་གི་རྣམ་པར་བཤད་པ།
      total_pages: 1540
      volume_number: 89
